### ISSUE TITLE
Added a bootstrap model

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/sampl5-experimental-logd-data#1]
Managed to put together a simple bootstrap model of the experiment last Friday.

See [wip_code/bootstrap_model.py](https://github.com/choderalab/sampl5-experimental-logd-data/blob/master/wip_code/bootstrap_model.py)

**Comment by bas-rustenburg** [comment]
I've updated the bootstrap model, and added documentation for it. Either read the comments, or browse the html file in a local web browser.

**Comment by jchodera** [comment]
That's the nicest goddamned IPython notebook I've ever seen.

**Comment by jchodera** [comment]
What should I be looking at to see the updated output for the bootstrap model?  Is it `logD_final.txt`?

**Comment by bas-rustenburg** [comment]
> That's the nicest goddamned IPython notebook I've ever seen.

That's because it's not an ipython notebook. :wink: 

The updated output is in `wip_code/logD_bootstrap.txt`, though I haven't run a lot of samples yet in that file, since I was debugging. Just 100 I think. I'll update it with more samples in a short bit, though it shouldn't affect the results too much.

**Comment by jchodera** [comment]
It might be useful to characterize both bias _and_ variance as a function of logD.  A plot of this, similar to [cells 32 and 33 here](https://github.com/choderalab/dispensing-errors-manuscript/blob/master/notebooks/echo-vs-tips.ipynb), might be useful!

Variance is probably best quantified as CV.

**Comment by bas-rustenburg** [comment]
Will take a look. Given the time constraints, I don't think I'll be able to discuss any results in detail in my talk. I'll add it to the data repository though, and to the documentation.

**Comment by jchodera** [comment]
OK!
